# This file contains values from Cookiecutter

default_context:
  project_name: "schedulebot"
  project_slug: "schedulebot"
  project_description: "Awesome `schedulebot` project!"
  username: "letisaudep"
  email: "letisaudep@gmail.com"
  vcs_remote_type: "github"
  minimal_python_version: "3.8"
  version: "0.1.0"
  line_length: "106"

  include_cli_example: "n"
  include_docker_sample: "n"
  include_tests_sample: "n"
  include_notebooks_sample: "y"
  include_mypy_linter: "n"
